<?php
/**
 * Created by PhpStorm.
 * User: jonaskortum
 * Date: 02.01.17
 * Time: 15:43
 */

function recipe_menu() {

    $items['rezept_erstellen_allgemein'] = array(
        'title' => 'Rezept erstellen',
        'access callback' => true,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('recipe_add_general_information_form'),
    );

    $items['rezept_bearbeiten/%'] = array(
        'title' => 'Rezept bearbeiten',
        'access callback' => true,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('recipe_change_information_form'),
        'file' => 'recipe_change_recipe.inc',
    );

    $items['rezept_erstellen_zutaten/%/%'] = array(
        'title' => 'Rezept erstellen',
        'access callback' => true,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('recipe_add_ingredients_form'),
    );

    $items['rezept_erstellen_vorschau/%'] = array(
        'title' => 'Rezept erstellen',
        'access callback' => true,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('recipe_get_preview_form'),
        'file' => 'recipe_get_preview.inc',
    );

    $items['rezeptansicht/%/%'] = array(
        'title' => 'Rezeptansicht',
        'access callback' => true,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('recipe_get_overview_overview'),
        'file' => 'recipe_get_overview.inc',
    );

    return $items;
}

function recipe_add_general_information_form() {

    $form['main'] = array(

        '#type' => 'fieldset',
        '#title' => t('Informationen zum Rezept'),
    );

    $form['main']['title'] = array(
        '#type' => 'textfield',
        '#require' => TRUE,
        '#title' => t('Name des Rezepts:'),
        '#required' => TRUE,
        '#default_value' => t('')
    );

    $form['main']['howto'] = array(
        '#type' => 'textarea',
        '#required' => TRUE,
        '#title' => t('Zubereitung:'),
    );

    $form['main']['time'] = array(
        '#type' => 'textfield',
        '#require' => TRUE,
        '#title' => t('Arbeitszeit'),
        '#required' => TRUE,
        '#size' => 3,
        '#field_suffix' => 'Minuten',
        '#default_value' => t('')
    );

    $form["main"]["difficulty"] = array(
        "#type" => "select",
        "#title" => t("Schwierigkeitsgrad"),
        '#required' => TRUE,
        "#options" => array("leicht" => "leicht", "mittel" => "mittel", "schwer" => "schwer"),
        "#default_value" => "leicht",
    );

    $form['main']['file'] = array(
        '#type' => 'file',
        '#name' => 'files[]',
        '#title' => t('Foto-Upload'),
        '#attributes' => array('multiple' => 'multiple'),
    );

    $form['main']['rating'] = array(
        '#type' => 'fivestar',
        '#stars' => 5,
        '#default_value' => 20,
        '#title' => t('Bewertung des Rezepts'),
    );

    $form['options'] = array(
        '#type' => 'fieldset',
        '#title' => t('Zutatenliste (max. 12)'),
        '#attributes' => array('class' => array('container-inline')),
    );
    $array = recipe_get_units();

    $form['options']['operation1'] = array(
        '#type' => 'textfield',
        '#required' => TRUE,
        '#size' => 4,
        '#title' => t('Zutatenanzahl:'),
        '#title_display' => 'invisible',
        '#default_value' => t('')
    );

    $form['options']['operation21'] = array(
        '#type' => 'select',
        '#title' => t('Operation'),
        '#required' => TRUE,
        '#title_display' => 'invisible',
        '#options' => $array,
        '#default_value' => 'approve',
    );

    $form['options']['operation31'] = array(
        '#type' => 'textfield',
        '#required' => TRUE,
        '#size' => 40,
        '#title' => t('Name der Zutat'),
        '#required' => TRUE,
        '#title_display' => 'invisible',
        '#default_value' => t('')
    );



    $test = "<br>";
    $form['options']['form_item'] = array(
        '#type' => 'markup',
        '#title' => t('My Form Item'),
        '#prefix' => $test
    );



    for ($i = 2; $i<=12; $i++) {

        $form['options']['operation' . $i] = array(
            '#type' => 'textfield',
            '#require' => TRUE,
            '#size' => 4,
            '#title' => t('Name des Rezepts:'),
            '#title_display' => 'invisible',
            '#default_value' => t('')
        );

        $form['options']['operation2' . $i] = array(
            '#type' => 'select',
            '#title' => t('Operation'),
            '#title_display' => 'invisible',
            '#options' => $array,
            '#default_value' => 'approve',
        );

        $form['options']['operation3' . $i] = array(
            '#type' => 'textfield',
            '#require' => TRUE,
            '#size' => 40,
            '#title' => t('Name des Rezepts:'),
            '#title_display' => 'invisible',
            '#default_value' => t('')
        );

        $test = "<br>";
        $form['options']['form_item2' . $i] = array(
            '#type' => 'markup',
            '#title' => t('My Form Item'),
            '#prefix' => $test
        );
    }

    $form["number_of_persons"] = array(
        "#type" => "select",
        "#title" => t("Personenanzahl"),
        '#required' => TRUE,
        "#options" => array("1" => "1", "2" => "2", "3" => "3", "4" => "4", "5" => "5", "6" => "6"),
        "#default_value" => "leicht",
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Speichern',
        '#submit' => array('recipe_go_to_ingredients')
    );

    return $form;
}

function recipe_go_to_ingredients($form, &$form_state) {
    global $user;
    $user_id = $user->uid;
    $titel = $form_state['values']['title'];
    $preparation = $form_state['values']['howto'];
    $work_time = $form_state['values']['time'];
    $difficulty = $form_state['values']['difficulty'];
    $rating = $form_state['values']['rating'];
    $number_of_persons = $form_state['values']['number_of_persons'];
    $sql = "INSERT INTO {recipe} (title, preparation, work_time, difficulty, number_of_persons, uid, rating) VALUES ('".$titel . "','".$preparation . "',".$work_time.",'".$difficulty."',".$number_of_persons . ",".$user_id.", ".$rating.")";
    drupal_set_message($sql);
    $myInsertID = db_query($sql, array(), array('return' => Database::RETURN_INSERT_ID));

    $num_files = count($_FILES['files']['name']);
    $main_path = "";

    for ($i = 0; $i < $num_files; $i++) {
        $file = file_save_upload($i, array(
            'file_validate_is_audio' => array(),
            'file_validate_extensions' => array('png pdf jpg jpeg mp3 mp4'),
            'file_validate_size' => array(5 * 1024 * 1024),
        ));
        if ($file) {
            if ($file = file_move($file, 'public://')) {
                $file->status = FILE_STATUS_PERMANENT;
                $sql = "UPDATE {file_managed} SET status = 1 WHERE fid > 0";
                db_query($sql);
                $path = substr($file->uri, 9);
                $sql = "INSERT INTO {recipe_data} VALUES (".$myInsertID.",'".$file->uri."')";
                $form_state['values']['file'][$i] = $file;
                db_query($sql);
            }
        } else {
            drupal_set_message("NOO");

        }
    }
    $array = recipe_get_units();

    for ($i = 1; $i<=12; $i++) {
        $eins = $form_state['values']['operation' . $i];
        $zwei = $array[$form_state['values']['operation2' . $i]];
        $drei = $form_state['values']['operation3' . $i];
        if(strlen($eins) > 0 && strlen($zwei) > 0 && strlen($drei) > 0) {
            $sql = "INSERT INTO {recipe_ingredient} VALUES (".$myInsertID.",'".$drei."',".$eins.",'".$zwei."')";
            db_query($sql);
        }
    }

    drupal_goto('/rezeptansicht/'.$myInsertID.'/4');
    drupal_set_message("Rezept erfolgreich gespeichert");
}

function recipe_go_back_to_general() {
    drupal_goto('/rezept_erstellen_allgemein');
}

function recipe_add_ingredients_form() {

    $array = recipe_get_units();

    $form['options'] = array(
        '#type' => 'fieldset',
        '#title' => t('Testbeschreibung'),
        '#attributes' => array('class' => array('container-inline')),
    );

    $num = recipe_get_number();

    for ($i = 1; $i<=$num; $i++) {
        $form['options']['operation' . $i] = array(
            '#type' => 'textfield',
            '#require' => TRUE,
            '#size' => 4,
            '#title' => t('Name des BLAH:'),
            '#title_display' => 'invisible',
            '#default_value' => t('')
        );

        $form['options']['operation2' . $i] = array(
            '#type' => 'select',
            '#title' => t('Operation'),
            '#title_display' => 'invisible',
            '#options' => $array,
            '#default_value' => 'approve',
        );

        $form['options']['operation3' . $i] = array(
            '#type' => 'textfield',
            '#require' => TRUE,
            '#title' => t('Name des Rezepts:'),
            '#title_display' => 'invisible',
            '#default_value' => t('')
        );

        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Zurück',
            '#submit' => array('recipe_go_back_to_general')
        );

        $form['more'] = array(
            '#type' => 'submit',
            '#value' => 'Zutaten hinzufügen',
            '#submit' => array('recipe_add_more_ingredients')
        );

        $form['back'] = array(
            '#type' => 'submit',
            '#value' => 'Weiter',
            '#submit' => array('recipe_get_ingredients')
        );
    }

    return $form;
}

function recipe_get_ingredients($form, &$form_state) {
    $num = arg(1);
    $array = recipe_get_units();
    $recipe_id = arg(2);
    for ($i = 1; $i<=$num; $i++) {
        $eins = $form_state['values']['operation' . $i];
        $zwei = $array[$form_state['values']['operation2' . $i]];
        $drei = $form_state['values']['operation3' . $i];
        if(strlen($eins) > 0 && strlen($zwei) > 0 && strlen($drei) > 0) {
            $sql = "INSERT INTO {recipe_ingredient} VALUES (".$recipe_id.",'".$drei."',".$eins.",'".$zwei."')";
            db_query($sql);
        }
        drupal_goto('/rezept_erstellen_vorschau/'.$recipe_id);
    }
}

function recipe_get_units() {
    $array = array();
    array_push($array, "Becher");
    array_push($array, "Beutel");
    array_push($array, "Blatt");
    array_push($array, "Bund");
    array_push($array, "cl");
    array_push($array, "Dose(n)");
    array_push($array, "einige");
    array_push($array, "EL");
    array_push($array, "EL, gehäuft");
    array_push($array, "EL, gestr.");
    array_push($array, "etwas");
    array_push($array, "evtl");
    array_push($array, "Flasche");
    array_push($array, "g");
    array_push($array, "Glas");
    array_push($array, "groß(e)");
    array_push($array, "kg");
    array_push($array, "klein(e)");
    array_push($array, "Knolle");
    array_push($array, "Kopf");
    array_push($array, "Kugel");
    array_push($array, "Liter");
    array_push($array, "mg");
    array_push($array, "ml");
    array_push($array, "Pck");
    array_push($array, "Prise");
    array_push($array, "Riegel");
    array_push($array, "Scheibe(n)");
    array_push($array, "Schuss");
    array_push($array, "Spritzer");
    array_push($array, "Stange(n)");
    array_push($array, "Stiel(e)");
    array_push($array, "Streifen");
    array_push($array, "Stück(e)");
    array_push($array, "Tafel(n)");
    array_push($array, "Tasse(n)");
    array_push($array, "TL");
    array_push($array, "TL, gehäuft");
    array_push($array, "TL, gestr.");
    array_push($array, "Tube(n)");
    array_push($array, "wenig");
    array_push($array, "Würfel");
    array_push($array, "x");
    array_push($array, "Zehe(n)");

    return $array;
}

function recipe_get_number() {
    $num = arg(1);
    return $num;
}

function recipe_add_more_ingredients() {
    $num = arg(1);
    $num = $num + 2;
    drupal_goto('/rezept_erstellen_zutaten/'.$num);
}

