<?php
/**
 * Created by PhpStorm.
 * User: jonaskortum
 * Date: 21.02.17
 * Time: 21:52
 */

function category_menu() {

    $items['category'] = array(
        'title' => 'Rezeptsuche',
        'access callback' => true,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('category_form'),
    );

    $items['add_to_category/%'] = array(
        'title' => 'Rezeptsuche',
        'access callback' => true,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('category_add_form'),
    );

    $items['add_recipe_to_category/%/%'] = array(
        'title' => 'Rezeptübersicht',
        'page callback' => 'category_add_recipe_to_category',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    $items['category_overview/%'] = array(
        'title' => 'Rezeptübersicht',
        'page callback' => 'category_category_overview',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    $items['delete_category/%'] = array(
        'title' => 'Rezeptübersicht',
        'page callback' => 'category_delete_category',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    $items['delete_recipe_from_category/%/%'] = array(
        'title' => 'Rezeptübersicht',
        'page callback' => 'category_delete_recipe_from_category',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function category_delete_recipe_from_category() {
    $recipe_id = arg(1);
    $category_id = arg(2);

    $sql = "DELETE FROM {recipe_user_category} WHERE category_id = ".$category_id." AND recipe_id = ".$recipe_id;
    db_query($sql);

    drupal_set_message("Rezept wurde aus der Kategorie entfernt");
    drupal_goto("category");
}

function category_delete_category() {

    $category_id = arg(1);
    $counter = 0;

    $sql = "SELECT * FROM {recipe_user_category} WHERE category_id = ".$category_id;
    $result = db_query($sql);
    foreach ($result as $item) {
        $counter++;
    }

    if($counter == 0) {
        $sql = "DELETE FROM {recipe_category} WHERE category_id =".$category_id;
        db_query($sql);
        drupal_set_message("Kategorie wurde entfernt!");
    } else {
        drupal_set_message("Sie können die Kategorie nicht entfernen, solange sich noch Rezepte darin befinden.", "error");
    }

    drupal_goto("category");
}


function category_category_overview() {
    $category = arg(1);
    global $base_url;
    global $user;


    $sql = "SELECT * FROM {recipe_user_category} as cat INNER JOIN {node} as node on cat.recipe_id = node.nid WHERE cat.uid = ".$user->uid." AND category_id = ".$category;
    $result = db_query($sql);

    $table_string = '<style>
.city {
 margin: 5px;
 max-width: 300px;
 width: 180px;
 height: 180px;
 padding: 3px;
 font-size: 0.7em;
}

.img {
    width:  200px;
    height: 150px;
}
</style>';


    $table_string .= '
    <table>
        <tr>
            <th  width="25%">Bild</th>
            <th>Name</th>
            <th>Aktion</th>
        </tr>';


    foreach ($result as $item) {

        $path2 = "http://www.gemaa-tempelsee.info/wp-content/uploads/2017/01/kein-bild-vorhanden.gif";

        $sql = "SELECT * FROM {field_data_field_recipe_image} WHERE entity_id = ".$item->recipe_id;
        $result = db_query($sql);
        foreach ($result as $item3) {
            $sql2 = "SELECT * FROM {file_managed} WHERE fid = ".$item3->field_recipe_image_fid;
            $result2 = db_query($sql2);
            foreach ($result2 as $item2) {
                $path2 = $item2->uri;
                $path2 = substr($path2, 8);
                $path2 = $base_url."/sites/default/files/".$path2;
            }
        }




        $table_string .= '
        <tr>
            <td align="right"><img class = "img "src="'.$path2.'" border="4" alt="Rose 1"></td>
            <td><a href="'.$base_url.'/node/'.$item->recipe_id.'">'.$item->title.'</td>
            <td><a href="'.$base_url.'/delete_recipe_from_category/'.$item->recipe_id.'/'.$category.'">aus Kategorie entfernen</td>
        </tr>';


    }
    $table_string .= '</table>';

    return $table_string;

}

function category_form() {

    global $user;
    global $base_url;

    $array = array();
    $temp = array();
    $sql = "SELECT * FROM {user_category} AS u INNER JOIN {recipe_category} as r ON u.category_id = r.category_id WHERE u.uid = ".$user->uid;
    $result = db_query($sql);

    $sql = "SELECT * FROM {recipe_user_category} WHERE uid = ".$user->uid;
    $result2 = db_query($sql);
    foreach ($result2 as $item) {
       array_push($array, $item->category_id);
    }

    $temp = array_count_values($array);

    $id = 1;

    $tempString = "<table><th>Nr.</th><th>Name</th> <th>Anzahl Rezepte</th><th>Aktion</th>";
    foreach ($result as $item) {
        if(array_key_exists ($item->category_id , $temp)) {
        } else {
            $temp[$item->category_id] = 0;
        }
        $tempString = $tempString . '<tr><td>'.$id.'</td><td>'.$item->category.'</td><td><a href="'.$base_url.'/category_overview/'.$item->category_id.'/">'.$temp[$item->category_id].'</td><td><a href="'.$base_url.'/delete_category/'.$item->category_id.'">Kategorie entfernen</a></td></tr>';
        $id++;
    }



    $tempString .= "</table>";

    $form['test']['form_item'] = array(
        '#type' => 'markup',
        '#title' => t('My Form Item'),
        '#prefix' => $tempString,
    );

    $form['test2']['category'] = array(
        '#type' => 'textfield',
        '#require' => TRUE,
        '#title' => t('Neue Kategorie anlegen'),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'neue Kategorie speichern',
        '#submit' => array('category_save_new_category')
    );
        return $form;
}

function category_add_form() {
    $array = array();
    $temp = array();
    global $base_url;
    global $user;
    $node = arg(1);

    $sql = "SELECT * FROM {user_category} AS u INNER JOIN {recipe_category} as r ON u.category_id = r.category_id WHERE u.uid = ".$user->uid;
    $result = db_query($sql);

    $sql = "SELECT * FROM {recipe_user_category} WHERE uid = ".$user->uid;
    $result2 = db_query($sql);
    foreach ($result2 as $item) {
        array_push($array, $item->category_id);
    }

    $temp = array_count_values($array);

    $tempString = "<table><th>Nr.</th><th>Name</th><th>Anzahl Rezepte</th><th>Aktion</th>";
    foreach ($result as $item) {

        if(array_key_exists ($item->category_id , $temp)) {
        } else {
            $temp[$item->category_id] = 0;
        }

        $tempString = $tempString . '<tr><td>1</td><td>'.$item->category.'</td><td>'.$temp[$item->category_id].'</td><td><a href="'.$base_url.'/add_recipe_to_category/'.$item->category_id.'/'.$node.'">Rezept hinzufügen</a></td></tr>';

    }



    $tempString .= "</table>";

    $form['test']['form_item'] = array(
        '#type' => 'markup',
        '#title' => t('My Form Item'),
        '#prefix' => $tempString,
    );

    return $form;

}

function category_save_new_category($form, &$form_state) {
    global $user;
    $cat = $form_state['values']['category'];

    if(strlen($cat) > 2) {
        $sql = "INSERT INTO {recipe_category} (category) VALUES ('".$cat."')";
        db_query($sql);


        $id = db_insert('recipe_category')
            ->fields(array(
                'category' => $cat,
            ))
            ->execute();


        $sql = "INSERT INTO {user_category} (uid, category_id) VALUES (".$user->uid.",".$id.")";
        db_query($sql);


        drupal_set_message("Kategorie erfolgreich angelegt");
    } else {
        drupal_set_message("Der Kategoriename muss mindestens 3 Zeichen enthalten!", "error");
    }



}

function category_add_recipe_to_category() {
    global $user;
    $counter = 0;
    $category = arg(1);
    $recipe = arg(2);

    $sql = "SELECT * FROM {recipe_user_category} WHERE recipe_id = ".$recipe." AND category_id = ".$category;
    $result = db_query($sql);
    foreach ($result as $item) {
        $counter++;
    }

    if($counter == 0) {
        $sql = "INSERT INTO {recipe_user_category} (recipe_id, uid, category_id) VALUES (".$recipe.",".$user->uid.",".$category.")";
        db_query($sql);
        drupal_set_message("Rezept wurde erfolgreich hinzugefügt!");
    } else {
        drupal_set_message("Rezept ist bereits in der Kategorie vorhanden!", "error");
    }




    drupal_goto("node/".$recipe);


}
