<?php
/**
 * Created by PhpStorm.
 * User: jonaskortum
 * Date: 23.01.17
 * Time: 18:06
 */

function cooking_proof_menu() {

    $items['vergangene_Gerichte'] = array(
        'title' => 'Rezeptübersicht',
        'page callback' => 'cooking_proof_get_cooking_history',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function cooking_proof_get_cooking_history() {

    global $user;

    $sql = "SELECT * FROM {recipe_cooked} WHERE uid = ".$user->uid;
    $result = db_query($sql);

    $tempString = "<table><th>Nr.</th><th>Rezeptname</th> <th> Datum</th><th>Aktionen</th>";

    $i=1;
    global $base_url;
    foreach ($result as $item) {
        $name = cooking_proof_get_recipe_name_from_id($item->recipe_id);
        $date = new DateTime($item->date);
        $deadline3 = $date->format('d.m.Y');

        //"<a href='/design_thinking_tool/delete_task/$pro->task_id'>löschen</a>
        $tempString .= "<tr><td>$i</td><td><a href='$base_url/rezeptansicht/$item->recipe_id/$name->number_of_persons'>$name->title</a></td><td>$deadline3</td><td></td></tr>";
        $i++;
    }
    
    $tempString .= "</table><br>";

    return $tempString;
}

function cooking_proof_get_recipe_name_from_id($recipe_id) {
    $recipe = "";
    $sql = "SELECT * FROM {recipe} WHERE recipe_id = " . $recipe_id;
    $result = db_query($sql);

    foreach ($result as $item) {
        $recipe = $item;
    }

    return $recipe;
}


