<?php
/**
 * Created by PhpStorm.
 * User: jonaskortum
 * Date: 23.01.17
 * Time: 18:06
 */

function cooking_proof_menu() {

    $items['vergangene_Gerichte'] = array(
        'title' => 'Rezeptübersicht',
        'page callback' => 'cooking_proof_get_cooking_history',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    $items['recipe_add_to_history'] = array(
        'title' => 'Rezeptübersicht',
        'page callback' => 'cooking_proof_add_to_history',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function cooking_proof_form_alter(&$form, &$form_state, $form_id) {
    drupal_set_message("TESTFORM");
    drupal_set_message($form_id);
    if (!strcmp($form_id, 'rezepthistorie_node_form')) {
        $form['title']['#disabled'] = TRUE;
    }
}

function cooking_proof_add_to_history() {

    $recipe_id = arg(1);

    $node2 = node_load($recipe_id);

    drupal_set_message($node2->title);

    global $user;

    $heute = date("Y-m-d H:i:s");

    db_insert('recipe_cooked')
        ->fields(array(
            'recipe_id' => $recipe_id,
            'date' => $heute,
            'uid' => $user->uid,
        ))
        ->execute();


    $node = new stdClass();
    $node->type = 'rezepthistorie';
    node_object_prepare($node);

    $node->language = LANGUAGE_NONE;

    $node->title = $node2->title;

    $date = new DateTime($heute);

    $date->sub(new DateInterval('PT1H'));
    $deadline2 = $date->format('Y-m-d H:i:s');

    $deadline2 = str_replace(" ", "T", $deadline2);

    $node->field_datum[$node->language][0]['value'] = $deadline2;
    $node->field_datum[$node->language][0]['timezone'] = "Europe/Berlin";
    $node->field_datum[$node->language][0]['timezone_db'] = "Europe/Berlin";

    $node->field_namenreferenz[$node->language][0]['value'] = $node2->title;
    $node->field_nutzerreferenz[$node->language][0]['value'] = $user->uid;


    $node->field_referenz[$node->language][0]['value'] = $node2->nid;

// Save node
    node_save($node);


    drupal_set_message("Rezept zur Historie hinzugefügt");
    drupal_goto("/node/".$recipe_id);

}


function cooking_proof_get_cooking_history() {

    global $user;

    $sql = "SELECT * FROM {recipe_cooked} WHERE uid = ".$user->uid;
    $result = db_query($sql);

    $tempString = "<table><th>Nr.</th><th>Rezeptname</th> <th> Datum</th><th>Aktionen</th>";

    $i=1;
    global $base_url;
    foreach ($result as $item) {
        $name = cooking_proof_get_recipe_name_from_id($item->recipe_id);
        $date = new DateTime($item->date);
        $deadline3 = $date->format('d.m.Y');

        //"<a href='/design_thinking_tool/delete_task/$pro->task_id'>löschen</a>
        $tempString .= "<tr><td>$i</td><td><a href='$base_url/rezeptansicht/$item->recipe_id/$name->number_of_persons'>$name->title</a></td><td>$deadline3</td><td></td></tr>";
        $i++;
    }
    
    $tempString .= "</table><br>";

    return $tempString;
}

function cooking_proof_get_recipe_name_from_id($recipe_id) {
    $recipe = "";
    $sql = "SELECT * FROM {recipe} WHERE recipe_id = " . $recipe_id;
    $result = db_query($sql);

    foreach ($result as $item) {
        $recipe = $item;
    }

    return $recipe;
}


