<?php
/**
 * Created by PhpStorm.
 * User: jonaskortum
 * Date: 28.02.17
 * Time: 17:56
 */

function recipe_search_menu() {
    $items['recipe_search'] = array(
        'access callback' => true,
        'page callback' => 'drupal_get_form',
        'access callback' => 'user_is_logged_in',
        'page arguments' => array('recipe_search_search_form'),
    );

    $items['term_search'] = array(
        'access callback' => true,
        'page callback' => 'drupal_get_form',
        'access callback' => 'user_is_logged_in',
        'page arguments' => array('recipe_search_term_search_form'),
    );

    $items['show_term_search/%'] = array(
        'title' => 'Ergebnisse der Suche nach einer Eigenschaft',
        'page callback' => 'recipe_search_search_for_term',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );


    $items['show_recipe_search/%'] = array(
        'title' => 'Ergebnisse der Sucht nach Rezepttitel',
        'page callback' => 'recipe_search_search_for_recipe_title',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function recipe_search_search_for_term() {
    global $base_url;
    $term_id = arg(1);

    $sql = "SELECT * FROM {taxonomy_index} WHERE tid = ".$term_id;
    $result = db_query($sql);

    $nodes = array();

    array_push($nodes, 0);
    foreach($result as $pro) {
        array_push($nodes, $pro->nid);
    }

    $list = implode(',', $nodes);

    $sql = "SELECT * FROM {node} WHERE nid IN ($list) ORDER BY title";
    $result = db_query($sql);

    $table_string = '<style>
.city {
 margin: 5px;
 max-width: 300px;
 width: 180px;
 height: 180px;
 padding: 3px;
 font-size: 0.7em;
}

.img {
    width:  200px;
    height: 150px;
}
</style>';


    $table_string .= '
    <table>
        <tr>
            <th  width="25%">Bild</th>
            <th>Name</th>
        </tr>';


    foreach ($result as $item) {

        $path2 = "http://www.gemaa-tempelsee.info/wp-content/uploads/2017/01/kein-bild-vorhanden.gif";

        $sql = "SELECT * FROM {field_data_field_recipe_image} WHERE entity_id = ".$item->nid;



        $result = db_query($sql);
        foreach ($result as $item3) {
            $sql2 = "SELECT * FROM {file_managed} WHERE fid = ".$item3->field_recipe_image_fid;
            $result2 = db_query($sql2);
            foreach ($result2 as $item2) {
                $path2 = $item2->uri;
                $path2 = substr($path2, 8);
                $path2 = $base_url."/sites/default/files/".$path2;
            }
        }

        $table_string .= '
        <tr>
            <td align="right"><img class = "img "src="'.$path2.'" border="4" alt="Rose 1"></td>
            <td><a href="'.$base_url.'/node/'.$item->nid.'">'.$item->title.'</td>

        </tr>';


    }
    $table_string .= '</table>';

    return $table_string;
}



function recipe_search_term_search_form() {

    $content = recipe_search_search_for_terms();

    $form['form_item'] = array(
        '#type' => 'markup',
        '#title' => t('My Form Item'),
        '#prefix' => $content,
    );

    return $form;
}

function recipe_search_search_form() {
    $form['bodyTextField'] = array(
        '#type' => 'textfield',
        '#require' => TRUE,
        '#title' => t('Hier den gewünschten Suchterm eintragen:'),
        '#default_value' => t('')
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Suche',
        '#submit' => array('recipe_search_redirect_to_recipe_title')
    );

    return $form;
}

function recipe_search_redirect_to_recipe_title(&$form, &$form_state) {
    $search = $form_state['values']['bodyTextField'];
    drupal_goto("show_recipe_search/".$search);
}


function recipe_search_search_for_recipe_title() {
    global $base_url;

    $search = arg(1);

    $sql = "SELECT * FROM {node} WHERE type = 'recipe' AND title LIKE '%".$search."%' ORDER BY title";
    $result = db_query($sql);
    $table_string = '<style>
.city {
 margin: 5px;
 max-width: 300px;
 width: 180px;
 height: 180px;
 padding: 3px;
 font-size: 0.7em;
}

.img {
    width:  200px;
    height: 150px;
}
</style>';


    $table_string .= '
    <table>
        <tr>
            <th  width="25%">Bild</th>
            <th>Name</th>
        </tr>';


    foreach ($result as $item) {

        $path2 = "http://www.gemaa-tempelsee.info/wp-content/uploads/2017/01/kein-bild-vorhanden.gif";

        $sql = "SELECT * FROM {field_data_field_recipe_image} WHERE entity_id = ".$item->nid;



        $result = db_query($sql);
        foreach ($result as $item3) {
            $sql2 = "SELECT * FROM {file_managed} WHERE fid = ".$item3->field_recipe_image_fid;
            $result2 = db_query($sql2);
            foreach ($result2 as $item2) {
                $path2 = $item2->uri;
                $path2 = substr($path2, 8);
                $path2 = $base_url."/sites/default/files/".$path2;
            }
        }

        $table_string .= '
        <tr>
            <td align="right"><img class = "img "src="'.$path2.'" border="4" alt="Rose 1"></td>
            <td><a href="'.$base_url.'/node/'.$item->nid.'">'.$item->title.'</td>

        </tr>';


    }
    $table_string .= '</table>';

    return $table_string;
}

function recipe_search_search_for_terms() {
    global $base_url;
    $sql = "SELECT * FROM {taxonomy_term_data} ORDER BY name";
    $result = db_query($sql);

    $string = "<ul>";
    foreach ($result as $item) {
        $string .="<li><a href='".$base_url."/show_term_search/".$item->tid."'>$item->name</a></li>";
    }
    $string .="</ul>";

    return $string;

}