<?php
/**
 * Created by PhpStorm.
 * User: jonaskortum
 * Date: 22.02.17
 * Time: 19:32
 */

function recipe_of_the_day_block_info() {
    $blocks = array();
    $blocks['my_block'] = array(
        'info' => t('My Custom Block'),
    );

    return $blocks;
}

function recipe_of_the_day_block_view($delta = '') {
    // This example is adapted from node.module.
    $block = array();

    switch ($delta) {
        case 'my_block':

            global $base_url;

            $nid = 0;
            $name = "";

            $sql = "SELECT * FROM {recipe} ORDER BY RAND() LIMIT 0,1;";
            $result = db_query($sql);
            foreach ($result as $item) {
                $nid = $item->nid;
            }

            $sql = "SELECT * FROM {node} WHERE nid = ".$nid;
            $result = db_query($sql);
            foreach ($result as $item) {
                $name = $item->title;
            }

            $sql = "SELECT * FROM {field_data_field_recipe_image} WHERE entity_id = ".$nid;
            $result = db_query($sql);
            foreach ($result as $item) {
                $sql2 = "SELECT * FROM {file_managed} WHERE fid = ".$item->field_recipe_image_fid;
                $result2 = db_query($sql2);
                foreach ($result2 as $item2) {
                    $path2 = $item2->uri;
                    $path2 = substr($path2, 8);
                    $path2 = $base_url."/sites/default/files/".$path2;
                }
            }

            $block['subject'] = t('Rezept des Tages');
            $block['content'] = ' <a href="'.$base_url.'/node/'.$nid.'"</a> <img class = "img "src="'.$path2.'" border="4" alt="Rose 1"><h3>'.$name.'</h3><br><br>';
            break;
    }
    return $block;
}