<?php
/**
 * Created by PhpStorm.
 * User: jonaskortum
 * Date: 22.02.17
 * Time: 19:32
 */

function recipe_of_the_day_block_info() {
    $blocks = array();
    $blocks['my_block'] = array(
        'info' => t('My Custom Block'),
    );

    return $blocks;
}

function recipe_of_the_day_cron() {
    drupal_set_message("Cron wurde vom Rezept des Tages ausgeführt!");

    $sql = "SELECT * FROM {recipe_of_the_day} ORDER BY recipe_of_the_day_id DESC LIMIT 1";
    $result = db_query($sql);

    if($result->rowCount() == 0) {
        $heute = date("Y-m-d");
        $recipe_id = 0;
        $sql = "SELECT * FROM {node} WHERE type ='recipe' ORDER BY RAND() LIMIT 1";
        $result = db_query($sql);

        foreach ($result as $item) {
            $recipe_id = $item->nid;
        }
        db_insert('recipe_of_the_day')
            ->fields(array(
                'date' => $heute,
                'recipe_id' => $recipe_id,
            ))
            ->execute();
    } else {
        foreach ($result as $item2) {

            if(!isToday($item2->date)) {
                $heute = date("Y-m-d");
                $recipe_id = 0;
                $sql = "SELECT * FROM {node} WHERE type ='recipe' ORDER BY RAND() LIMIT 1";
                $result2 = db_query($sql);

                foreach ($result2 as $item) {
                    $recipe_id = $item->nid;
                }
                drupal_set_message("Letzter Eintrag ist nicht von heute, neue Rezept_ID: ".$recipe_id);

                db_insert('recipe_of_the_day')
                    ->fields(array(
                        'date' => $heute,
                        'recipe_id' => $recipe_id,
                    ))
                    ->execute();
            } else {
                drupal_set_message("Eintrag ist von heute");
            }
        }
    }
}

function isToday($time)
{
    return (strtotime($time) === strtotime('today'));
}


function recipe_of_the_day_block_view($delta = '') {
    $block = array();

    switch ($delta) {
        case 'my_block':

            global $base_url;

            $nid = 0;
            $path2 = "http://www.gemaa-tempelsee.info/wp-content/uploads/2017/01/kein-bild-vorhanden.gif";
            $name = "";

            $sql = "SELECT * FROM {recipe_of_the_day} ORDER BY recipe_of_the_day_id ASC";
            $result = db_query($sql);
            foreach ($result as $item) {
                $nid = $item->recipe_id;
            }

            $sql = "SELECT * FROM {node} WHERE nid = ".$nid;
            $result = db_query($sql);
            foreach ($result as $item) {
                $name = $item->title;
            }

            $sql = "SELECT * FROM {field_data_field_recipe_image} WHERE entity_id = ".$nid;
            $result = db_query($sql);
            foreach ($result as $item) {
                $sql2 = "SELECT * FROM {file_managed} WHERE fid = ".$item->field_recipe_image_fid;
                $result2 = db_query($sql2);
                foreach ($result2 as $item2) {
                    $path2 = $item2->uri;
                    $path2 = substr($path2, 8);
                    $path2 = $base_url."/sites/default/files/".$path2;
                }
            }

            $block['subject'] = t('Rezept des Tages');
            $block['content'] = ' <a href="'.$base_url.'/node/'.$nid.'"</a> <img class = "img "src="'.$path2.'" border="4" alt="Rose 1"><h3>'.$name.'</h3><br><br>';
            break;
    }
    return $block;
}