<?php
/**
 * Created by PhpStorm.
 * User: jonaskortum
 * Date: 02.01.17
 * Time: 15:43
 */

function recipe_overview_menu() {

    $items['rezeptuebersicht'] = array(
        'title' => 'Rezeptübersicht',
        'page callback' => 'recipe_overview_get_recipes',
        'access callback' => 'user_is_logged_in',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function recipe_overview_get_recipes() {
    $array = recipe_overview_get_recipes2();
    $test = recipe_overview_create_content($array);




    return $test;
}

function recipe_overview_create_content($recipes) {
    $test = "";
    $name = "";
    $path2 = "";
    $bla = '
    <style>
.city {
 float: left;
 margin: 5px;
 max-width: 300px;
 width: 180px;
 height: 180px;
 padding: 3px;
 font-size: 0.7em;
}

.img {
    width:  200px;
    height: 150px;
}
</style>
';

    global $base_url;




    for($i = 0; $i<sizeof($recipes); $i++) {

        $path = "";
        $name = "";
        $sql = "SELECT * FROM {node} WHERE nid = ".$recipes[$i];
        $result = db_query($sql);
        foreach ($result as $item) {
            $name = $item->title;
        }

        $path2 = "http://www.gemaa-tempelsee.info/wp-content/uploads/2017/01/kein-bild-vorhanden.gif";

        $sql = "SELECT * FROM {field_data_field_recipe_image} WHERE entity_id = ".$recipes[$i];
        $result = db_query($sql);
        foreach ($result as $item) {
            $sql2 = "SELECT * FROM {file_managed} WHERE fid = ".$item->field_recipe_image_fid;
            $result2 = db_query($sql2);
            foreach ($result2 as $item2) {
                $path2 = $item2->uri;
                $path2 = substr($path2, 8);
                $path2 = $base_url."/sites/default/files/".$path2;
            }


        }






        $bla .= '

 <tr><td>

 <div class="city">
 <a href="'.$base_url.'/node/'.$recipes[$i].'"><img class = "img "src="'.$path2.'" border="4" alt="Rose 1"><h3>'.$name.'</h3></a><br><br><br>
 </div>

 ';




/*

        $path2 = "";
        $recipe_id = 16;
        $sql = "SELECT * FROM {recipe_data} WHERE recipe_id = ".$recipes[$i];
        $result2 = db_query($sql);

        foreach ($result2 as $r2) {
            $path2 = substr($r2->data_path, 9);
        }

        if(!strcmp($path2, "")) {
            $path2 = "Beispielbild.jpeg";
        }

        $sql2 = "SELECT * FROM {recipe} WHERE recipe_id = ".$recipes[$i];
        $nameResult = db_query($sql2);
        foreach ($nameResult as $item) {
            $name = $item->title;
        }

        $bla .= '

 <tr><td>

 <div class="city">
 <img class = "img "src="'.$path.$path2.'" border="4" alt="Rose 1"><h3><a href="/kochbuch/rezeptansicht/'.$recipes[$i].'/4">'.$name.'</a></h3>
 </div>

 ';*/

        /*
                $test .= '
               <td>
               <div style="overflow-x:auto;" class="img150">
               <img src="https://wikispeicher.ch/w/images/6/6c/Beispielbild.jpg" width="150" height="150" border="0" alt="Rose 1">
               Bilduntertext zur Rose 1
               </div>';*/








//<img src="'.$path.$path2.'" width="150" height="150" border="0" alt="'.$path.'Beispielbild.jpeg">

        /*
                $test .='
        <div class="img150">
        <a href="/kochbuch/rezeptansicht/'.$recipes[$i].'/4">'.$name.'</a>
        </div>
        ';
                if ($i+1%4 == 0 && $i>0) {
                    $test .= '<br style="clear: both;">

         ';}*/



    }

    $test .= "</table>";
    $bla .= "</table>";

    return $bla;
}

function recipe_overview_get_recipes2() {

    $recipes = array();

    $sql = "SELECT * FROM {recipe} as re INNER JOIN {node} as node ON re.nid = node.nid ORDER BY node.title";
    $result = db_query($sql);

    foreach ($result as $r) {
        array_push($recipes, $r->nid);
    }

    return $recipes;
}
