<?php
/**
 * Created by PhpStorm.
 * User: jonaskortum
 * Date: 23.01.17
 * Time: 18:06
 */

function text_boxes_form($form, &$form_state)
{
    $number = 0;
    $addTextbox = false;

    $form['text_lists'] = array
    (
        '#tree' => true,
        '#theme' => 'my_list_theme',
        '#prefix' => '<div id="wrapper">',
        '#suffix' => '</div>',
    );

    if (array_key_exists('triggering_element', $form_state) &&
        array_key_exists('#name', $form_state['triggering_element']) &&
        $form_state['triggering_element']['#name'] == 'Add'
    ) {
        $addTextbox = true;
    }

    if (array_key_exists('values', $form_state) && array_key_exists('text_lists', $form_state['values']))
    {
        foreach ($form_state['values']['text_lists'] as $element) {
            $form['text_lists'][$number]['text'] = array(
                '#type'  => 'textfield',
            );
            $number++;
        }
    }
    if ($addTextbox) {
        $form['text_lists'][$number]['text'] = array(
            '#type'  => 'textfield',
        );
    }

    $form['add_button'] = array(
        '#type' => 'button',
        '#name' => 'Add',
        '#ajax' => array(
            'callback' => 'ajax_add_textbox_callback',
            'wrapper'  => 'wrapper',
            'method'   => 'replace',
            'effect'   => 'fade',
        ),
        '#value' => t('Add'),
    );

    return $form;
}

function ajax_add_textbox_callback($form, $form_state)
{
    return $form['text_lists'];
}

function text_boxes_menu()
{
    $items = array();

    $items['text_boxes'] = array(
        'title'           => 'Text Boxes',
        'description'     => 'Text Boxes',
        'page callback'   => 'drupal_get_form',
        'page arguments'  => array('text_boxes_form'),
        'access callback' => array(TRUE),
        'type'            => MENU_CALLBACK,
    );

    return $items;
}