<?php
/**
 * Created by PhpStorm.
 * User: jonaskortum
 * Date: 02.01.17
 * Time: 15:43
 */

function ingredient_search_menu() {

    $items['suche_nach_zutat/%'] = array(
        'title' => 'Rezeptsuche',
        'access callback' => true,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('ingredient_search_search_form'),
    );

    return $items;
}

function ingredient_search_search_form() {

    $ingredient = arg(1);
    $array = ingredient_search_get_recipe_with_ingredient();
    $test = ingredient_search_create_content($array);

    $test = "<h1>$test</h1>";

    $form['test']['form_item'] = array(
        '#type' => 'markup',
        '#title' => t('My Form Item'),
        '#prefix' => $test
    );

    return $form;
}

function ingredient_search_get_recipe_with_ingredient() {

    $ingredient = arg(1);
    $recipes = array();

    $sql = "SELECT DISTINCT recipe_id FROM {recipe_ingredient} WHERE ingredient LIKE '%".$ingredient."%' ORDER BY recipe_id ASC";
    drupal_set_message($sql);
    $result = db_query($sql);

    foreach ($result as $r) {
        array_push($recipes, $r->recipe_id);
    }

    return $recipes;
}

function ingredient_search_create_content($recipes) {
    $test = "";
    $name = "";
    $path2 = "";
    $test .= '
<style>.img150
{
float: left;
width: 150px;
padding: 3px;
font-size: 0.7em;
} </style>
';
    $path = "http://localhost/kochbuch/sites/default/files/";

    for($i = 0; $i<sizeof($recipes); $i++) {
    $recipe_id = 16;
    $sql = "SELECT * FROM {recipe_data} WHERE recipe_id = ".$recipes[$i];
    $result2 = db_query($sql);

    foreach ($result2 as $r2) {
        $path2 = substr($r2->data_path, 9);
    }

        if(!strcmp($path2, "")) {
            $path2 = "Beispielbild.jpeg";
        }

    $sql2 = "SELECT * FROM {recipe} WHERE recipe_id = ".$recipes[$i];
    $nameResult = db_query($sql2);
        foreach ($nameResult as $item) {
            $name = $item->title;
    }


        $test .='
<div class="img150">
<img src="'.$path.$path2.'" width="150" height="150" border="0" alt="'.$path.'Beispielbild.jpeg">
<a href="/kochbuch/rezept_erstellen_vorschau/'.$recipes[$i].'">'.$name.'</a>
</div>
';
        if ($i+1%4 == 0 && $i>0) {
        $test .= '<br style="clear: both;">

 ';}


    }



    return $test;
}

/*

 */

